export const musicData = [
  {
    section: 'Sidebar',
    playlists: [
      {
        id: 1,
        imgUrl: 'img/playlist01.png',
        alt: "day's playlist",
      },
      {
        id: 2,
        imgUrl: 'img/playlist02.png',
        alt: "day's playlist",
      },
      {
        id: 3,
        imgUrl: 'img/playlist03.png',
        alt: "day's playlist",
      },
    ],
  },
  {
    section: 'Tracklist',
    tracks: [
      {
        id: 4,
        title: 'Cuilt',
        titleSpan: '',
        author: 'Welcome Reality',
        album: 'Welcome Reality',
        time: '4:44',
      },
      {
        id: 5,
        title: 'Elektro',
        titleSpan: '',
        author: 'Dynoro Outwork, Mr. Gee',
        album: 'Elektro',
        time: '2:22',
      },
      {
        id: 6,
        title: 'I’m Fire',
        titleSpan: '',
        author: 'Ali Bakgor',
        album: 'I’m Fire',
        time: '2:22',
      },
      {
        id: 7,
        title: 'Non Stop',
        titleSpan: ' (Remix)',
        author: 'Стоункат, Psychopath',
        album: 'Run Run',
        time: '2:54',
      },
      {
        id: 8,
        title: 'Run Run',
        titleSpan: ' (feat. AR/CO)',
        author: 'Jaded, Will Clarke, AR/CO',
        album: 'Welcome Reality',
        time: '4:44',
      },
      {
        id: 9,
        title: 'Eyes on Fire',
        titleSpan: ' (Zeds Dead Remix)',
        author: 'Blue Foundation, Zeds Dead',
        album: 'Eyes on Fire',
        time: '5:20',
      },
      {
        id: 10,
        title: 'Mucho Bien',
        titleSpan: '(Hi Profile Remix)',
        author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
        album: 'Mucho Bien',
        time: '3:41',
      },
      {
        id: 11,
        title: 'Knives n Cherries',
        titleSpan: '',
        author: 'minthaze',
        album: 'Captivating',
        time: '1:48',
      },
      {
        id: 12,
        title: 'How Deep Is Your Love',
        titleSpan: '',
        author: 'Calvin Harris, Disciples',
        album: 'How Deep Is Your Love',
        time: '3:32',
      },
      {
        id: 13,
        title: 'Morena',
        titleSpan: '',
        author: 'Tom Boxer',
        album: 'Soundz Made in Romania',
        time: '3:36',
      },
      {
        id: 14,
        title: 'How Deep Is Your Love',
        titleSpan: '',
        author: 'Calvin Harris, Disciples',
        album: 'How Deep Is Your Love',
        time: '4:44',
      },
    ],
  }
]
